title: "Huntersville Rock Art"
description: "Custom-painted spirit rocks for birthdays, schools, and events in Huntersville, NC and nearby."
url: "https://ethancboone.github.io"
baseurl: "/huntersville-rock-painting"
image:
  path: "/assets/og.jpg"
  alt: "Custom-painted spirit rocks in Huntersville, NC"

twitter_username: ""
social:
  name: "Huntersville Rock Art"
  links: []
  facebook: "https://www.facebook.com/your-page"
  instagram: "https://www.instagram.com/your-handle"

collections:
  gallery:
    output: true
    permalink: /gallery/:name/
  testimonials:
    output: true
    permalink: /testimonials/:name/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: "_gallery"
    values:
      layout: gallery_item
  - scope:
      path: ""
    values:
      layout: page

permalink: pretty
