backend:
  name: github
  repo: ethancboone/huntersville-rock-painting
  branch: main
  base_url: https://api.github.com

media_folder: "assets/gallery"
public_folder: "/assets/gallery"

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "_gallery"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Date, name: date, widget: datetime}
      - {label: Tags, name: tags, widget: list, default: [birthday]}
      - {label: Image, name: image, widget: image}
      - {label: Alt Text, name: alt, widget: string}
      - {label: Caption, name: caption, widget: text}

  - name: "packages"
    label: "Packages"
    folder: "_packages"
    create: true
    fields:
      - {label: Name, name: name, widget: string}
      - {label: Price, name: price, widget: string}
      - {label: Short, name: short, widget: string}
      - {label: Includes, name: includes, widget: list}
      - {label: Stripe Link, name: stripe_link, widget: string}

  - name: "testimonials"
    label: "Testimonials"
    folder: "_testimonials"
    create: true
    fields:
      - {label: Author, name: author, widget: string}
      - {label: Quote, name: quote, widget: text}
